"""Modified World model

Revision ID: 157876905fb5
Revises: d01f46cf9fd9
Create Date: 2025-04-26 09:13:05.386728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157876905fb5'
down_revision: Union[str, None] = 'd01f46cf9fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('worlds', 'full_description')
    op.drop_column('worlds', 'genre')
    op.drop_column('worlds', 'short_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('short_description', sa.VARCHAR(), nullable=True))
    op.add_column('worlds', sa.Column('genre', sa.TEXT(), nullable=False))
    op.add_column('worlds', sa.Column('full_description', sa.TEXT(), nullable=True))
    op.drop_column('worlds', 'description')
    # ### end Alembic commands ###
