"""add cover field to worlds

Revision ID: 72276e6a4b76
Revises: 9093e9db8d5a
Create Date: 2025-05-23 09:38:26.553889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72276e6a4b76'
down_revision: Union[str, None] = '9093e9db8d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('cover', sa.String(), nullable=True))
    op.drop_column('worlds', 'cover_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('cover_image_path', sa.VARCHAR(), nullable=True))
    op.drop_column('worlds', 'cover')
    # ### end Alembic commands ###
