"""add cover field to organisations

Revision ID: 786d65607b8b
Revises: 72276e6a4b76
Create Date: 2025-05-23 13:58:41.771489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786d65607b8b'
down_revision: Union[str, None] = '72276e6a4b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('cover', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('images_json', sa.Text(), nullable=True))
    op.drop_column('organizations', 'logo_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_image_path', sa.VARCHAR(), nullable=True))
    op.drop_column('organizations', 'images_json')
    op.drop_column('organizations', 'cover')
    # ### end Alembic commands ###
