"""Rename image_path to cover and add tag to character

Revision ID: 8b56dd1e3043
Revises: ed7462ebaf43
Create Date: 2025-05-29 22:45:42.118561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b56dd1e3043'
down_revision: Union[str, None] = 'ed7462ebaf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('cover', sa.String(), nullable=True))
    op.drop_column('characters', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('photo_path', sa.VARCHAR(), nullable=True))
    op.drop_column('characters', 'cover')
    # ### end Alembic commands ###
